name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Setup Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build with Hexo
      run: npx hexo g

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        branch: gh-pages